document.write("<link rel = 'stylesheet' type = 'text/css' href = '/sofast/html/plugin/jquery/css/jquery.dataTables.css'>");
document.write("<link rel = 'stylesheet' type = 'text/css' href = '/sofast/html/plugin/bootstrap/css/bootstrap.css'>");
document.write("<link rel = 'stylesheet' type = 'text/css' href = '/sofast/html/css/dashboard.css'>");
document.write("<link rel = 'stylesheet' type = 'text/css' href = '/sofast/html/css/main.css'>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/jquery/js/jquery-1.11.3.min.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/jquery/js/jquery.dataTables.min.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/angular/js/angular.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/angular/js/angular-datatables.min.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/angular_query/underscore/underscore.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/angular_query/angular-query-builder-templates.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/angular_query/angular-animate.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/angular_query/bootstrap3-typeahead.min.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/angular_query/angular-query-builder.min.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/bootstrap/js/ui-bootstrap-tpls-1.3.3.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/bootstrap/js/popper.min.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/plugin/bootstrap/js/bootstrap.min.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/js/ui.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/js/datatables.js'></script>");
document.write("<script  type='text/javascript' src='/sofast/html/js/main.js'></script>");